export default [
  {
      "ID": 0,
      "date": "2018-08-04T14:17:48.296Z",
      "isPreSession": true,
      "moods": [
        "tired",
        "sad",
        "insecure",
        "anxious",
        "inspired",
        "motivated",
        "empty",
      ],
      "notMoods": [
        "happy",
        "relaxed",
        "annoyed",
        "loved",
        "calm",
        "caring",
        "grateful",
        "angry",
      ],
  },
  {
      "ID": 1,
      "date": "2018-08-04T14:18:48.296Z",
      "isPreSession": false,
      "moods": [
        "tired",
        "insecure",
        "inspired",
        "motivated",
        "empty",
        "calm",
        "caring",
      ],
      "notMoods": [
        "happy",        
        "anxious",
        "relaxed",
        "sad",
        "annoyed",
        "loved",
        "grateful",
        "angry",
      ],
  },
  {
    "ID": 2,
    "date": "2018-08-05T14:17:48.296Z",
    "isPreSession": true,
    "moods": [
        "insecure",
        "happy",
        "inspired",
        "tired",
        "anxious",
        "relaxed",
        "sad",
        "annoyed",
    ],
    "notMoods": [
        "loved",
        "empty",
        "angry",
        "motivated",
        "grateful",
        "calm",
        "caring",
    ],
  },
  {
      "ID": 3,
      "date": "2018-08-05T14:19:48.296Z",
      "isPreSession": false,
      "moods": [
        "insecure",
        "happy",
        "inspired",
        "motivated",
        "grateful",
        "calm",
        "caring",
      ],
      "notMoods": [
        "tired",
        "anxious",
        "relaxed",
        "sad",
        "annoyed",
        "loved",
        "empty",
        "angry",
      ],
  },
  {
    "ID": 4,
    "date": "2018-08-06T14:17:48.296Z",
    "isPreSession": true,
    "moods": [
      "tired",
      "anxious",
      "relaxed",
      "sad",
      "annoyed",
      "loved",
      "empty",
      "angry",
    ],
    "notMoods": [
      "insecure",
        "happy",
        "inspired",
        "motivated",
        "grateful",
        "calm",
        "caring",
    ],
  },
  {
    "ID": 5,
    "date": "2018-08-06T14:19:48.296Z",
    "isPreSession": false,
    "moods": [
      "tired",
      "anxious",
      "relaxed",
      "sad",
      "empty",
    ],
    "notMoods": [
      "insecure",
        "happy",
        "annoyed",
        "loved",
        "angry",
        "inspired",
        "motivated",
        "grateful",
        "calm",
        "caring",
    ],
  },
  {
    "ID": 6,
    "date": "2018-08-07T14:19:50.296Z",
    "isPreSession": true,
    "moods": [
      "insecure",
        "happy",
        "relaxed",
        "loved",
        "inspired",
        "motivated",
        "grateful",
        "calm",
        "caring",
    ],
    "notMoods": [
      "tired",
      "annoyed",
      "anxious",
      "angry",
      "sad",
      "empty",
    ],
  },
  {
    "ID": 7,
    "date": "2018-08-07T14:20:48.296Z",
    "isPreSession": false,
    "moods": [
      "insecure",
        "happy",
        "relaxed",
        "loved",
        "inspired",
        "motivated",
        "grateful",
        "calm",
        "caring",
    ],
    "notMoods": [
      "tired",
      "annoyed",
      "anxious",
      "angry",
      "sad",
      "empty",
    ],
  },
  {
    "ID": 8,
    "date": "2018-08-08T14:19:50.296Z",
    "isPreSession": true,
    "moods": [
      "inspired",
      "motivated",
      "grateful",
      "calm",
      "caring",
      "angry",
      "sad",
      "empty",
    ],
    "notMoods": [
      "insecure",
      "happy",
      "relaxed",
      "loved",
      "tired",
      "annoyed",
      "anxious",
    ],
  },
  {
    "ID": 9,
    "date": "2018-08-08T14:21:48.296Z",
    "isPreSession": false,
    "moods": [
      "happy",
      "loved",
      "inspired",
      "motivated",
      "grateful",
      "calm",
      "caring",
      "angry",
    ],
    "notMoods": [
      "sad",
      "empty",
      "insecure",
      "relaxed",
      "tired",
      "annoyed",
      "anxious",
    ],
  },
  {
    "ID": 10,
    "date": "2018-08-09T14:11:50.296Z",
    "isPreSession": true,
    "moods": [
      "tired",
      "annoyed",
      "anxious",
      "sad",
      "empty",
      "insecure",
      "angry",
    ],
    "notMoods": [
      "relaxed",
      "happy",
      "loved",
      "inspired",
      "motivated",
      "grateful",
      "calm",
      "caring",
    ],
  },
  {
    "ID": 11,
    "date": "2018-08-09T14:13:48.296Z",
    "isPreSession": false,
    "moods": [
      "relaxed",
      "happy",
      "loved",
      "inspired",
      "motivated",
      "grateful",
      "calm",
      "caring",
    ],
    "notMoods": [
      "tired",
      "annoyed",
      "anxious",
      "sad",
      "empty",
      "insecure",
      "angry",
    ],
  },
  {
    "ID": 12,
    "date": "2018-08-09T14:11:50.296Z",
    "isPreSession": true,
    "moods": [
      "loved",
      "inspired",
      "motivated",
      "grateful",
      "calm",
      "caring",
      "tired",
      "annoyed",
    ],
    "notMoods": [
      "relaxed",
      "happy",
      "anxious",
      "sad",
      "empty",
      "insecure",
      "angry",
    ],
  },
  {
    "ID": 13,
    "date": "2018-08-09T14:13:48.296Z",
    "isPreSession": false,
    "moods": [
      "loved",
      "inspired",
      "motivated",
      "grateful",
      "caring",
      "tired",
      "anxious",
      "annoyed",
    ],
    "notMoods": [
      "calm",
      "relaxed",
      "happy",
      "sad",
      "empty",
      "insecure",
      "angry",
    ],
  },
  {
    "ID": 14,
    "date": "2018-08-09T14:11:50.296Z",
    "isPreSession": true,
    "moods": [
      "annoyed",
      "anxious",
      "sad",
      "empty",
      "relaxed",
      "happy",
      "loved",
    ],
    "notMoods": [
      "insecure",
      "angry",
      "tired",
      "inspired",
      "motivated",
      "grateful",
      "calm",
      "caring",
    ],
  },
  {
    "ID": 15,
    "date": "2018-08-09T14:13:48.296Z",
    "isPreSession": false,
    "moods": [
      "calm",
      "caring",
      "annoyed",
      "anxious",
      "sad",
      "empty",
      "relaxed",
      "happy",
      "loved",
    ],
    "notMoods": [
      "insecure",
      "angry",
      "tired",
      "inspired",
      "motivated",
      "grateful",
    ],
  },
  {
    "ID": 16,
    "date": "2018-08-09T14:11:50.296Z",
    "isPreSession": true,
    "moods": [
      "relaxed",
      "happy",
      "loved",
      "grateful",
      "calm",
      "caring",
    ],
    "notMoods": [
      "inspired",
      "motivated",
      "tired",
      "annoyed",
      "anxious",
      "sad",
      "empty",
      "insecure",
      "angry",
    ],
  },
  {
    "ID": 17,
    "date": "2018-08-09T14:13:48.296Z",
    "isPreSession": false,
    "moods": [
      "relaxed",
      "happy",
      "loved",
      "grateful",
      "calm",
      "caring",
    ],
    "notMoods": [
      "inspired",
      "motivated",
      "tired",
      "annoyed",
      "anxious",
      "sad",
      "empty",
      "insecure",
      "angry",
    ],
  },
  {
    "ID": 18,
    "date": "2018-08-09T14:11:50.296Z",
    "isPreSession": true,
    "moods": [
      "sad",
      "empty",
      "insecure",
      "angry",
    ],
    "notMoods": [
      "tired",
      "annoyed",
      "anxious",
      "grateful",
      "calm",
      "caring",
      "relaxed",
      "happy",
      "loved",
      "inspired",
      "motivated",
    ],
  },
  {
    "ID": 19,
    "date": "2018-08-09T14:13:48.296Z",
    "isPreSession": false,
    "moods": [
      "angry",
      "grateful",
      "calm",
      "caring",
    ],
    "notMoods": [
      "sad",
      "empty",
      "insecure",
      "tired",
      "annoyed",
      "anxious",
      "relaxed",
      "happy",
      "loved",
      "inspired",
      "motivated",
    ],
  },
  {
    "ID": 20,
    "date": "2018-08-09T14:11:50.296Z",
    "isPreSession": true,
    "moods": [
      "tired",
      "annoyed",
      "anxious",
      "inspired",
      "motivated",
      "grateful",
      "calm",
      "caring",
    ],
    "notMoods": [
      "relaxed",
      "happy",
      "loved",
      "sad",
      "empty",
      "insecure",
      "angry",
    ],
  },
  {
    "ID": 21,
    "date": "2018-08-09T14:13:48.296Z",
    "isPreSession": false,
    "moods": [
      "inspired",
      "motivated",
      "grateful",

    ],
    "notMoods": [
      "tired",
      "annoyed",
      "anxious",
      "calm",
      "caring",
      "relaxed",
      "happy",
      "loved",
      "sad",
      "empty",
      "insecure",
      "angry",
    ],
  },
]

[
  {
    "ID": 0,
    "preSessionID": 0,
    "postSessionID": 1,
    "time": "2018-08-04T14:17:48.296Z",
  },
  {
    "ID": 1,
    "preSessionID": 2,
    "postSessionID": 3,
    "time": "2018-08-05T14:17:48.296Z",
  },
  {
    "ID": 2,
    "preSessionID": 4,
    "postSessionID": 5,
    "time": "2018-08-06T14:17:48.296Z",
  },
  {
    "ID": 3,
    "preSessionID": 6,
    "postSessionID": 7,
    "time": "2018-08-07T14:17:48.296Z",
  },
  {
    "ID": 4,
    "preSessionID": 8,
    "postSessionID": 9,
    "time": "2018-08-08T14:17:48.296Z",
  },
  {
    "ID": 5,
    "preSessionID": 10,
    "postSessionID": 11,
    "time": "2018-08-09T14:17:48.296Z",
  },
  {
    "ID": 6,
    "preSessionID": 12,
    "postSessionID": 13,
    "time": "2018-08-10T14:17:48.296Z",
  },
  {
    "ID": 7,
    "preSessionID": 14,
    "postSessionID": 15,
    "time": "2018-08-11T14:17:48.296Z",
  },
  {
    "ID": 8,
    "preSessionID": 16,
    "postSessionID": 17,
    "time": "2018-08-12T14:17:48.296Z",
  },
  {
    "ID": 9,
    "preSessionID": 18,
    "postSessionID": 19,
    "time": "2018-08-13T14:17:48.296Z",
  },
  {
    "ID": 10,
    "preSessionID": 20,
    "postSessionID": 21,
    "time": "2018-08-14T14:17:48.296Z",
  },